//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFUygulama2.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyhistory
    {
        public int id { get; set; }
        public string productname { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> productid { get; set; }
    }
}
