//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFUygulama2.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string productname { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> stock { get; set; }
        public string imagebase64 { get; set; }
    }
}
