//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFUygulama2.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ticaretEntities : DbContext
    {
        public ticaretEntities()
            : base("name=ticaretEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buyhistory> buyhistory { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<product> product { get; set; }
    }
}
